### PR TITLE
threaded version

### PR DESCRIPTION
**Pull request by veksha**
1. <s>created 50ms timer for query thread. it will make sure thread will get cpu time. (timer spins only if thread is alive)</s> bad idea
2. created 250ms timer (MainThread). it will wake other threads and show Output panel and scroll to end. (timer spins forever). it will be boosted to 50ms interval when threads are active.
3. enabled daemon mode on all threads. (so threads (if alive) will be terminated on app exit)

please try this PR, @Vivalzar, @Alexey-T 

related issue: https://github.com/Alexey-T/CudaText/issues/4713

### CODE REVIEW

**Comment by veksha** [comment]
still something is not right.

non-threaded is faster then threaded on this query:
`exec DBMS_LOCK.sleep(1);`
(only on first call after CudaText restart)

**Comment by Alexey-T** [comment]
I cannot test, sorry, didnot setup mySQL and forgot its configs.

**Comment by veksha** [comment]
> I cannot test, sorry, didnot setup mySQL and forgot its configs.

you can setup SQLite. it's easy. no server required. https://youtu.be/U7nfe4adDw8

**Comment by veksha** [comment]
@Alexey-T I noticed that scrollbar of Output memo is painted wrong when lines are added to Output panel and the following code is run:
```python
    ed_output.set_caret(0, cnt-1)
    ed_output.set_prop(PROP_LINE_TOP, cnt-1)
```

**Comment by Vivalzar** [comment]
How can I test your latest work? The command **Install from Git...** will fetch your latest commits?

**Comment by veksha** [comment]
yes. url - https://github.com/veksha/cuda_sqltools , choose branch - threaded

**Comment by veksha** [comment]
maybe you may need to delete plugin folder first

**Comment by Alexey-T** [comment]
@veksha 

>I noticed that scrollbar of Output memo is painted wrong when lines are added to Output panel and the following code is run:

Can you show small repro plugin?

**Comment by Vivalzar** [comment]
Works great for me. 😀

It gives back control to the user immediately after selecting a connection, even while retrieving tables/columns/functions.
The panel displays the output correctly.
The **thread_timeout** option works now.
There are no error on exit regarding threads still running.

Thank you for your great work!

**Comment by Alexey-T** [comment]
pls mark PR as 'ready'.

**Comment by veksha** [comment]
added status message. ready for review/merge.

**Comment by Vivalzar** [comment]
> added status message.

Thank you very much for that! I was trying to do it, but it kept crashing to desktop...

**Comment by Alexey-T** [comment]
f-strings - please no, Cud supports pre-Py3.6 versions (even 3.4 on winxp).

**Comment by veksha** [comment]
@Alexey-T , better?

**Comment by Vivalzar** [comment]
See my comment in the original issue:
https://github.com/Alexey-T/CudaText/issues/4713#issuecomment-1369780185

**Pull request merged**
